import{S as p,a as g,i as h}from"./assets/vendor-DjDxajEQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const u of i.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function l(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function s(e){if(e.ep)return;e.ep=!0;const i=l(e);fetch(e.href,i)}})();const v=new p(".list-img a");async function f(r,t){const l=r.map(s=>`<li class="imgAdded">
                <a href="${s.largeImageURL}"> 
                    <img src="${s.webformatURL}" alt="${s.tags}" width="360" height="152">
                </a>
                <div class="descr">
                    <p><b>Likes</b> ${s.likes}</p>
                    <p><b>Views</b> ${s.views}</p>
                    <p><b>Comments</b> ${s.comments}</p>
                    <p><b>Downloads</b> ${s.downloads}</p>
                </div>
            </li>`).join("");t.insertAdjacentHTML("beforeend",l),v.refresh()}async function y(r,t,l){try{const e=(await g.get("https://pixabay.com/api/",{params:{key:"45999766-9f9a6b82db6e56573d0cf5f49",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:l,page:t}})).data;return e.hits.length<=0?(h.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),[]):e.hits}catch(s){h.error({title:"Error",message:"An error occurred while fetching the images. Please try again later.",position:"topRight"}),console.error(s)}}const L=document.querySelector(".formImg"),m=document.querySelector(".list-img"),o=document.querySelector(".loader"),a=document.querySelector(".fetchPhotos"),b=document.getElementById("search-img");let d=1,c=15,n="";L.addEventListener("submit",async r=>{if(r.preventDefault(),m.innerHTML="",o.classList.remove("visually-hidden"),a.classList.add("visually-hidden"),d=1,n=b.value.trim(),n!=="")try{const t=await y(n,d,c);f(t,m),t.length>=c?a.classList.remove("visually-hidden"):a.classList.add("visually-hidden"),o.classList.add("visually-hidden")}catch(t){console.log(t),a.classList.add("visually-hidden"),o.classList.add("visually-hidden")}else o.classList.add("visually-hidden"),h.error({title:"Error",message:"Please enter a valid search query!",position:"topRight"})});a.addEventListener("click",async()=>{try{a.classList.add("visually-hidden"),o.classList.remove("visually-hidden"),d+=1;const r=await y(n,d,c);f(r,m),r.length>=c?a.classList.remove("visually-hidden"):a.classList.add("visually-hidden"),o.classList.add("visually-hidden")}catch(r){console.log(r),a.classList.add("visually-hidden"),o.classList.add("visually-hidden")}});
//# sourceMappingURL=index.js.map
